# Data Collection

## Objective

The objective of this notebook is to collect historical stock market data from Yahoo Finance using the `yfinance` library.

### Companies Included

### 🇺🇸 US Companies
- Apple (AAPL)
- Microsoft (MSFT)
- NVIDIA (NVDA)
- Amazon (AMZN)

### 🇮🇳 Indian Companies
- Reliance Industries (RELIANCE.NS)
- TCS (TCS.NS)
- HDFC Bank (HDFCBANK.NS)
- Infosys (INFY.NS)

### Time Period

- Start Date : 2015-01-01
- End Date : 2025-12-31

The downloaded datasets will be stored in the `data/raw` directory.

In [8]:
import os
import sys
import pandas as pd


sys.path.append(os.path.abspath("../src"))

%load_ext autoreload
%autoreload 2

from download_data import download_stocks

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [9]:
download_stocks("D:\\PROGRAMING\\Python\\Project\\StockVision\\data\\raw")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume,Company
Date,,,,,,
2015-01-01,359.981018,361.366678,356.790344,358.987338,2002764,INFY.NS
2015-01-02,367.055237,368.121852,359.543485,359.543485,6778320,INFY.NS
2015-01-05,363.901001,370.118254,360.546230,366.453541,9937024,INFY.NS
2015-01-06,356.298126,361.913723,352.633412,361.002102,9667316,INFY.NS
2015-01-07,358.002838,360.044861,355.532335,358.267199,7249916,INFY.NS
...,...,...,...,...,...,...
2025-12-23,1632.963745,1643.437060,1621.315775,1643.437060,6593060,INFY.NS
2025-12-24,1628.167480,1632.278472,1617.498330,1625.818291,4271167,INFY.NS
2025-12-26,1621.022095,1633.453168,1616.715267,1628.167521,2006491,INFY.NS
2025-12-29,1609.863525,1637.662008,1602.424525,1622.881866,4062817,INFY.NS
2025-12-30,1587.252808,1612.995794,1582.554548,1612.114833,9395937,INFY.NS

## Verify Downloaded Dataset

In [10]:
apple = pd.read_csv("../data/raw/AAPL.csv")

apple.head()

         Date      Close       High        Low       Open     Volume Company
0  2015-01-02  24.192610  24.659512  23.754473  24.648447  212818400    AAPL
1  2015-01-05  23.511055  24.042129  23.325180  23.962467  257142000    AAPL
2  2015-01-06  23.513266  23.772163  23.152577  23.575224  263188400    AAPL
3  2015-01-07  23.842985  23.942561  23.610640  23.721280  160423600    AAPL
4  2015-01-08  24.759081  24.816614  24.053195  24.170475  237458000    AAPL

In [11]:
apple.info()

<class 'pandas.DataFrame'>
RangeIndex: 2765 entries, 0 to 2764
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     2765 non-null   str
 1   Close    2765 non-null   float64
 2   High     2765 non-null   float64
 3   Low      2765 non-null   float64
 4   Open     2765 non-null   float64
 5   Volume   2765 non-null   int64
 6   Company  2765 non-null   str
dtypes: float64(4), int64(1), str(2)
memory usage: 151.3 KB

In [12]:
print("Dataset Shape:", apple.shape)

Dataset Shape: (2765, 7)

## Observations

- Historical stock data was successfully downloaded from Yahoo Finance.
- Eight companies from the US and Indian stock markets were selected.
- Each dataset contains Open, High, Low, Close, Volume, Date, and Company columns.
- Raw datasets were stored in the `data/raw` directory and will be used in the next stage of the project.